spring.application.name=CitaFacil-EsSalud

# ===== Base de datos PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/citafacil
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:46394058}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Servidor =====
server.port=8080

# ===== JWT (seguridad) =====
app.jwt.secret=${JWT_SECRET:CambiaEstaClaveSecretaPorUnaLargaYSeguraEnProduccion1234567890}
app.jwt.expiration-ms=86400000
